Name:           ros-hydro-scitos-description
Version:        0.1.0
Release:        0%{?dist}
Summary:        ROS scitos_description package

Group:          Development/Libraries
License:        BSD
URL:            http://github.com/strands-project/scitos_common
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  ros-hydro-catkin

%description
The scitos_description package contains the description (mechanical, kinematic,
visual, etc.) of the SCITOS robot.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Thu Oct 23 2014 Lars Kunze <l.kunze@cs.bham.ac.uk> - 0.1.0-0
- Autogenerated by Bloom

* Wed Sep 10 2014 Lars Kunze <l.kunze@cs.bham.ac.uk> - 0.0.4-1
- Autogenerated by Bloom

* Thu Sep 04 2014 Lars Kunze <l.kunze@cs.bham.ac.uk> - 0.0.4-0
- Autogenerated by Bloom

